# Generated by Django 3.0.4 on 2020-09-21 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseball_app', '0002_auto_20200915_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('man', '男性'), ('woman', '女性'), ('other', 'その他')], max_length=5, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('picher', 'ピッチャー'), ('catcher', 'キャッチャー'), ('first', 'ファースト'), ('second', 'セカンド'), ('third', 'サード'), ('short', 'ショート'), ('left', 'レフト'), ('center', 'センター'), ('right', 'ライト'), ('coach', 'コーチ陣')], max_length=7, verbose_name='ポジション'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
