# Generated by Django 3.0.4 on 2020-09-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0003_auto_20200921_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('picher', 'ピッチャー'), ('catcher', 'キャッチャー'), ('first', 'ファースト'), ('second', 'セカンド'), ('third', 'サード'), ('short', 'ショート'), ('left', 'レフト'), ('center', 'センター'), ('right', 'ライト')], max_length=7, verbose_name='ポジション'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
