# Generated by Django 3.0.4 on 2020-09-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0005_profile_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='チーム名'),
        ),
    ]
