# Generated by Django 3.0.4 on 2020-10-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0009_batting_discrimination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactedresults',
            name='added_number_of_outs',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=20, verbose_name='増えたアウトカウント'),
        ),
        migrations.AlterField(
            model_name='uncontactedresults',
            name='added_number_of_outs',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=20, verbose_name='増えたアウトカウント'),
        ),
    ]
