# Generated by Django 3.0.4 on 2020-10-01 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0010_auto_20201001_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactedresults',
            name='added_number_of_outs',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=20, null=True, verbose_name='増えたアウトカウント'),
        ),
        migrations.AlterField(
            model_name='contactedresults',
            name='score',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, null=True, verbose_name='得点'),
        ),
        migrations.AlterField(
            model_name='pitting',
            name='number_of_pitches',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='球数'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)], verbose_name='身長(cm)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uniform_number',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='背番号'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)], verbose_name='体重(kg)'),
        ),
        migrations.AlterField(
            model_name='uncontactedresults',
            name='added_number_of_outs',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=20, null=True, verbose_name='増えたアウトカウント'),
        ),
        migrations.AlterField(
            model_name='uncontactedresults',
            name='score',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, null=True, verbose_name='得点'),
        ),
    ]
