# Generated by Django 3.0.4 on 2020-10-01 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0011_auto_20201001_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitting',
            name='number_of_pitches',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='球数'),
        ),
    ]
