# Generated by Django 3.0.4 on 2020-10-02 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0013_auto_20201001_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactedresults',
            name='added_number_of_outs',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='増えたアウトカウント'),
        ),
        migrations.AlterField(
            model_name='contactedresults',
            name='score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='得点'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uniform_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='背番号'),
        ),
        migrations.AlterField(
            model_name='uncontactedresults',
            name='added_number_of_outs',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='増えたアウトカウント'),
        ),
        migrations.AlterField(
            model_name='uncontactedresults',
            name='score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='得点'),
        ),
    ]
