# Generated by Django 3.0.4 on 2020-10-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0014_auto_20201002_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitting',
            name='widpit_or_passedball',
            field=models.BooleanField(default=False, verbose_name='ワイルドピッチ,パスボール'),
        ),
        migrations.AddField(
            model_name='uncontactedresults',
            name='uncaught_third_strike',
            field=models.BooleanField(default=False, verbose_name='振り逃げ'),
        ),
        migrations.AlterField(
            model_name='batting',
            name='batting',
            field=models.CharField(choices=[('swing_and_missed', '空振り'), ('swing_and_contact', 'ゴロ・フライ・ライナー・単打・長打'), ('foul', 'ファール'), ('taken', '見送り'), ('sacrifice', '犠打'), ('other', 'その他')], max_length=20, verbose_name='打者の行動'),
        ),
        migrations.AlterField(
            model_name='uncontactedresults',
            name='uncontacted_results',
            field=models.CharField(choices=[('strikeout', '三振'), ('base_on_ball', '四球'), ('hit_by_pitch', '死球'), ('other', 'その他')], max_length=20, verbose_name='結果'),
        ),
    ]
