# Generated by Django 3.0.4 on 2020-10-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0016_auto_20201004_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='batting_handedness',
            field=models.CharField(choices=[('right_handed_batting', '右打ち'), ('left_handed_batting', '左打ち'), ('switch_hitter', '両打ち')], max_length=20, verbose_name='打ち方（必須）'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('man', '男性'), ('woman', '女性'), ('other', 'その他')], max_length=5, null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='氏名（必須）'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('picher', 'ピッチャー'), ('catcher', 'キャッチャー'), ('first', 'ファースト'), ('second', 'セカンド'), ('third', 'サード'), ('short', 'ショート'), ('left', 'レフト'), ('center', 'センター'), ('right', 'ライト')], max_length=7, verbose_name='ポジション（必須）'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='throwing_handedness',
            field=models.CharField(choices=[('right_handed_throwing', '右投げ'), ('left_handed_throwing', '左投げ'), ('switch_picher', '両投げ')], max_length=21, verbose_name='投げ方（必須）'),
        ),
    ]
