# Generated by Django 3.0.4 on 2020-10-04 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0017_auto_20201004_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitting',
            old_name='widpit_or_passedball',
            new_name='wildpit_or_passedball',
        ),
    ]
