# Generated by Django 3.0.4 on 2020-10-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0019_auto_20201004_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batting',
            name='discrimination',
            field=models.CharField(choices=[('undecided', '打席結果未定'), ('decided_with_contacted', '打席結果確定(フライ、ヒット等ボールとのコンタクト有り)'), ('decided_with_uncontacted', '打席結果確定(三振、四球等ボールとのコンタクト無し)')], max_length=30, verbose_name='打席結果'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日(形式:年-月-日 {入力例:1990-01-01})'),
        ),
    ]
