# Generated by Django 3.0.4 on 2020-10-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0020_auto_20201005_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batting',
            name='batting',
            field=models.CharField(choices=[('swing_and_missed', '空振り'), ('swing_and_contact', 'スイングかつボールとコンタクト有（フライ、ヒット等）'), ('foul', 'ファール'), ('taken', '見送り'), ('sacrifice', '犠打'), ('other', 'その他')], max_length=20, verbose_name='打者行動'),
        ),
    ]
